# Generated by Django 4.0.1 on 2022-01-27 03:02

import colorfield.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publish_date', models.DateField(default=datetime.date.today, editable=False, verbose_name='date published')),
                ('updated_date', models.DateField(default=datetime.date.today, editable=False, verbose_name='date updated')),
                ('body', markdownx.models.MarkdownxField()),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publish_date', models.DateField(default=datetime.date.today, editable=False, verbose_name='date published')),
                ('updated_date', models.DateField(default=datetime.date.today, editable=False, verbose_name='date updated')),
                ('body', markdownx.models.MarkdownxField()),
                ('accent_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('page', models.IntegerField()),
                ('body_markdown', models.TextField(null=True)),
                ('participant_posts_are_editable', models.BooleanField(default=True, verbose_name='Allow Participants to edit posts')),
                ('participant_posts_can_be_shared', models.BooleanField(default=True, verbose_name='Allow Participants to share posts')),
                ('force_participant_post_sharing', models.BooleanField(default=False, verbose_name='Force Participant Posts to be shared with the group')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.module')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', markdownx.models.MarkdownxField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date published')),
                ('body', markdownx.models.MarkdownxField()),
                ('body_markdown', models.TextField(default='')),
                ('body_markdown_short', models.TextField(default='')),
                ('editable', models.BooleanField(default=True)),
                ('shared', models.BooleanField(default=None, null=True)),
                ('sharable', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='classroom.topic')),
            ],
        ),
    ]
