# Generated by Django 4.0.2 on 2022-02-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_bingocard_program_module_enabled_module_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enrollment',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to='classroom.Program'),
        ),
    ]
